version: '3'
services:
  mysql_user:
    image: mysql
    container_name: mysql_user
    ports:
     - "3301:3306"
    links:
      - redis_user
    environment:
     - MYSQL_DATABASE=user
     - MYSQL_ROOT_PASSWORD=qwer1234!
  mysql_compare_cart:
    image: mysql
    container_name: compare_cart_db_mysql
    ports:
     - "3302:3306"
    environment:
     - MYSQL_DATABASE=compare_cart
     - MYSQL_ROOT_PASSWORD=qwer1234
  mysql_api_usage:
    image: mysql
    container_name: mysql_api_usage
    ports:
     - "3303:3306"
    environment:
     - MYSQL_DATABASE=apiusage
     - MYSQL_ROOT_PASSWORD=qwer1234!
  redis_product:
    image: redis
    container_name: redis_product
    ports:
      - 3304:6379
  mysql_filter_keyword:
    image: mysql
    container_name: mysql_filter_keywor
    ports:
     - "3305:3306"
    environment:
     - MYSQL_DATABASE=filter_keyword
     - MYSQL_ROOT_PASSWORD=qwer1234!
  redis_user:
    image: redis
    container_name: redis_user
    ports:
      - 3307:6379
  module_user:
    image: openjdk
    container_name: module_user
    command: "java -jar /usr/src/myapp/module-user.jar --spring.config.additional-location=file:/usr/src/myapp/"
    ports:
     - "6301:6301"
    volumes:
     - ./module-user/build/libs:/usr/src/myapp
    depends_on:
      - redis_user
      - mysql_user
