version: '2'
services:
  mysql_user:
    image: mysql
    container_name: user_db_mysql
    ports:
     - "3301:3306"
    environment:
     - MYSQL_DATABASE=user
     - MYSQL_ROOT_PASSWORD=qwer1234!
  mysql_compare_cart:
    image: mysql
    container_name: compare_cart_db_mysql
    ports:
     - "3302:3306"
    environment:
     - MYSQL_DATABASE=compare_cart
     - MYSQL_ROOT_PASSWORD=qwer1234
  mysql_api_usage:
    image: mysql
    container_name: apiusage_db_mysql
    ports:
     - "3303:3306"
    environment:
     - MYSQL_DATABASE=apiusage
     - MYSQL_ROOT_PASSWORD=qwer1234!!
